In [2]:
""" Deep Learning | Perceptron

Objectives:

1. Understand the structure and functionality of the perceptron
2. Implement a perceptron
3. Train a model for binary classification
"""

import torch
import torch.nn as nn
import numpy as np

In [3]:
X = np.array([
    [0.0, 0.0], 
    [0.0, 1.0], 
    [1.0, 0.0], 
    [1.0, 1.0]
])

In [6]:
X = torch.Tensor(X)
print(type(X))

<class 'torch.Tensor'>


In [22]:
X = torch.Tensor(
    [
        [0.0, 0.0, 0.0], 
        [0.0, 1.0, 0.0], 
        [1.0, 0.0, 0.0], 
        [1.0, 1.0, 1.0]
    ]
)

Y = torch.Tensor(
    [
        [0.0], 
        [0.0], 
        [0.0], 
        [1.0]
    ]
)

In [9]:
print(np.random.rand(5))
print(torch.rand(5))

[0.33225416 0.59562392 0.21921744 0.27528145 0.97477743]
tensor([0.1902, 0.9075, 0.1429, 0.5963, 0.8635])


In [12]:
t = torch.rand(5)
t = t.sum(axis=0)
print(t)

tensor(2.7107)


In [14]:
"""
X = [x1, x2, x3]
W = [w1, w2, w3]
b
"""

class Perceptron(nn.Module):
    def __init__(self, input_size):
        super(Perceptron, self).__init__()
        
        self.input_size = input_size
        self.weight = nn.Parameter(
            torch.randn(input_size)
        )
        self.bias = nn.Parameter(
            torch.zeros(1)
        )
        
    def forward(self, x):
        z = x @ self.weight + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

In [15]:
model = Perceptron(input_size=3)

In [18]:
torch.manual_seed(42)

x = torch.randn(3)
print(x)

y_pred = model(x)
print(y_pred)

tensor([0.3367, 0.1288, 0.2345])
tensor([0.4479], grad_fn=<SigmoidBackward0>)


In [19]:
print(*model.parameters())

Parameter containing:
tensor([ 0.0512, -1.1093, -0.3557], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)


In [20]:
""" Cost function """

criterion = nn.BCELoss()

""" Optimizers """
optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.0001
)

In [36]:
y_pred = model(X)
y_pred = y_pred.unsqueeze(axis=1)
print(y_pred.shape)

torch.Size([4, 1])


torch.Size([4, 1])


In [37]:
def train_model(model, epochs):
    for epoch in range(epochs):
        """ Prediction (Forward Propagation) """
        y_pred = model(X)
        
        """ Loss calculation """
        loss = criterion(y_pred.unsqueeze(axis=1), Y)

        """ Calculate gradient """
        optimizer.zero_grad()
        loss.backward() # (Backward propagation)

        """ Update weight """
        optimizer.step() # w1 = w1 - lr * dw1
        
        if epoch % 1000 == 0:
            print(f'Epoch: {epoch}, Loss: {loss.item():.4f}')

In [39]:
train_model(model, epochs=100000)

Epoch: 0, Loss: 0.4421
Epoch: 1000, Loss: 0.4153
Epoch: 2000, Loss: 0.3900
Epoch: 3000, Loss: 0.3662
Epoch: 4000, Loss: 0.3439
Epoch: 5000, Loss: 0.3229
Epoch: 6000, Loss: 0.3032
Epoch: 7000, Loss: 0.2848
Epoch: 8000, Loss: 0.2675
Epoch: 9000, Loss: 0.2514
Epoch: 10000, Loss: 0.2363
Epoch: 11000, Loss: 0.2222
Epoch: 12000, Loss: 0.2090
Epoch: 13000, Loss: 0.1966
Epoch: 14000, Loss: 0.1849
Epoch: 15000, Loss: 0.1740
Epoch: 16000, Loss: 0.1637
Epoch: 17000, Loss: 0.1540
Epoch: 18000, Loss: 0.1448
Epoch: 19000, Loss: 0.1362
Epoch: 20000, Loss: 0.1281
Epoch: 21000, Loss: 0.1204
Epoch: 22000, Loss: 0.1132
Epoch: 23000, Loss: 0.1065
Epoch: 24000, Loss: 0.1001
Epoch: 25000, Loss: 0.0940
Epoch: 26000, Loss: 0.0884
Epoch: 27000, Loss: 0.0831
Epoch: 28000, Loss: 0.0780
Epoch: 29000, Loss: 0.0733
Epoch: 30000, Loss: 0.0689
Epoch: 31000, Loss: 0.0647
Epoch: 32000, Loss: 0.0608
Epoch: 33000, Loss: 0.0571
Epoch: 34000, Loss: 0.0536
Epoch: 35000, Loss: 0.0504
Epoch: 36000, Loss: 0.0473
Epoch: 37000, 

In [40]:
def predict(model, X):
    """ Model evaludation mode """
    model.eval()
    with torch.no_grad():
        test_output = model(X)
    return test_output

predict(model, X)

tensor([3.0572e-05, 1.1229e-03, 1.1229e-03, 9.9888e-01])

In [44]:
model.state_dict()['bias']

tensor([-10.3954])

In [45]:
"""save a model"""

torch.save(model.state_dict(), 'my_model.pt')

In [47]:
""" Load the model 
1. For prediction
2. For resuming training.
"""

loaded_model = Perceptron(input_size=3)

loaded_model.load_state_dict(torch.load('my_model.pt'))

<All keys matched successfully>

In [48]:
loaded_model(X)

tensor([3.0572e-05, 1.1229e-03, 1.1229e-03, 9.9888e-01],
       grad_fn=<SigmoidBackward0>)